#!/usr/bin/env bash

interval=${1:-3}

while true; do
    cat /sys/devices/virtual/thermal/thermal_zone0/temp | tr -d '\n'
    echo -en '\t'
    cat /sys/devices/virtual/thermal/thermal_zone1/temp | tr -d '\n'
    echo -en '\t'
    cat /sys/devices/virtual/thermal/thermal_zone2/temp | tr -d '\n'
    echo -en '\t'
    cat /sys/devices/virtual/thermal/thermal_zone3/temp | tr -d '\n'
    sleep $interval
    echo -en '\r'
done
